import { makeStyles } from '@material-ui/core/styles';

const useStyles = makeStyles({
  root: {
    width: '100%',
    height: '100%',
    background: 'rgba(0,0,0,.65)',
    zIndex: 999,
    position: 'fixed',
    top: 0,
    left: 0,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  wrapper: {
    borderRadius: 12,
    width: 400,
    background: '#FFFFFF',
    overflow: 'hidden',
  },
  header: {
    width: 400,
    padding: 16,
    background: '#FFFFFF',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderBottom: '1px solid #dbdbdb',
    flexDirection: 'column',
  },
  headerText: {
    padding: 0,
    fontSize: 20,
    fontWeight: 600,
    margin: '16px 0px',
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: '50%',
  },
  input: {
    width: 400,
    height: 48,
    padding: '4px 8px',
    background: '#FFFFFF',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderBottom: '1px solid #dbdbdb',
    cursor: 'pointer',
    fontSize: 14,
    color: '#0095f6',
    fontWeight: 600,
  },
  item: {
    width: 400,
    height: 48,
    padding: '4px 8px',
    background: '#FFFFFF',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderBottom: '1px solid #dbdbdb',
    cursor: 'pointer',
  },
  text: {
    padding: 0,
    margin: 0,
    fontSize: 14,
  },
  textRed: {
    padding: 0,
    margin: 0,
    fontSize: 14,
    color: '#ed4956',
    fontWeight: 600,
  },
});
export default useStyles;
