import { makeStyles } from '@material-ui/core/styles';
const useStyles = makeStyles({
  root: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  wrapper: {
    width: 975,
    padding: '30px 20px 0px 20px',
  },
  infomationWrapper: {
    marginBottom: 44,
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  avatarBox: {
    width: 293,
    marginRight: 30,
    display: 'flex',
    justifyContent: 'center',
  },
  avatar: { width: 150, height: 150, borderRadius: '50%' },
  infomationBox: {
    width: 652,
    height: 200,
  },
  infomationTop: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 20,
  },
  infomationTopName: {
    fontSize: 28,
    fontWeight: 400,
    padding: 0,
    margin: 0,
    color: '#262626',
  },
  infomationTopEdit: {
    border: '1px solid #dbdbdb',
    background: '#FFFFFF',
    borderRadius: 4,
    marginLeft: 20,
    padding: '5px 9px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  settings: {
    width: 24,
    height: 24,
    marginLeft: 10,
    cursor: 'pointer',
  },
  postDetailBox: {
    display: 'flex',
    marginBottom: 20,
  },
  postDetail: {
    marginRight: 40,
    fontSize: 16,
  },
  postDetailText: {
    fontWeight: 600,
    color: '#262626',
  },
  postUserName: {
    fontWeight: 600,
    fontSize: 16,
    padding: 0,
    margin: 0,
    width: '100%',
  },
  postBio: { fontSize: 16, padding: 0, margin: 0, width: '100%' },
  tabWrapper: {
    width: '100%',
    height: 100,
    borderTop: '1px solid #dbdbdb',
  },
  tabBox: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
  },
  tab: {
    height: 52,
    marginRight: 60,
    display: 'flex',
    alignItems: 'center',
    borderTop: '1px solid #000000',
    marginTop: -1,
    cursor: 'pointer',
  },
  tabImg: {
    width: 12,
    height: 12,
  },
  tabText: {
    fontSize: 12,
    marginLeft: 6,
  },
  list: {
    width: '100%',
  },
  listItem: {
    width: 293,
    height: 293,
    marginBottom: 28,
    float: 'left',
    position: 'relative',
    cursor: 'pointer',
  },
  listItemImg: {
    width: 293,
    height: 293,
  },
  listItemHover: {
    width: 293,
    height: 293,
    zIndex: 9,
    position: 'absolute',
    top: 0,
    left: 0,
    background: 'rgba(0, 0, 0,0.1)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  listItemInside: { display: 'flex', alignItems: 'center' },
  listItemIcon: {
    width: 20,
    height: 20,
    color: '#FFFFFF',
  },
  listItemText: {
    margin: 0,
    padding: 0,
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  dialog: {
    width: '100%',
    height: '100%',
    background: 'rgba(0,0,0,.65)',
    zIndex: 999,
    position: 'fixed',
    top: 0,
    overflow: 'hidden',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dialogContent: {
    borderRadius: 12,
    width: 400,
    background: '#FFFFFF',
  },
  dialogItemWrapper: {
    width: 400,
    height: 48,
    padding: '4px 8px',
    background: '#FFFFFF',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderBottom: '1px solid #dbdbdb',
    cursor: 'pointer',
  },
  dialogItemWrapper1st: {
    width: 400,
    height: 48,
    padding: '4px 8px',
    background: '#FFFFFF',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderBottom: '1px solid #dbdbdb',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    cursor: 'pointer',
  },
  dialogItemWrapperLast: {
    width: 400,
    height: 48,
    padding: '4px 8px',
    background: '#FFFFFF',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    cursor: 'pointer',
  },
  dialogItemText: {
    padding: 0,
    margin: 0,
    fontSize: 14,
  },
});
export default useStyles;
