import { makeStyles } from '@material-ui/core/styles';
const useStyles = makeStyles({
  root: {
    width: '100%',
    height: '100%',
    background: 'rgba(0,0,0,.65)',
    zIndex: 999,
    position: 'fixed',
    top: 0,
    left: 0,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  wrapper: {
    borderRadius: 12,
    width: 400,
    background: '#FFFFFF',
    overflow: 'hidden',
    position: 'relative',
  },
  rotation: {
    width: 25,
    height: 25,
    position: 'absolute',
    top: 145,
    right: 16,
    zIndex: 9999,
    cursor: 'pointer',
  },
  item: {
    width: '100%',
    height: 42,
    background: '#FFFFFF',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderBottom: '1px solid #dbdbdb',
    cursor: 'pointer',
    position: 'relative',
  },
  leftIcon: {
    height: 42,
    width: 42,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    left: 0,
    position: 'absolute',
    cursor: 'pointer',
  },
  rightIcon: {
    height: 42,
    width: 60,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    right: 0,
    position: 'absolute',
    fontWeight: 500,
    color: '#0095F6',
  },
  centerItem: {
    width: 'calc(100%-46px)',
    height: 42,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontWeight: 500,
  },
  icon: {
    width: 14,
    height: 14,
    cursor: 'pointer',
  },
  text: {
    padding: 0,
    margin: 0,
    fontSize: 14,
  },
  textRed: {
    padding: 0,
    margin: 0,
    fontSize: 14,
    color: '#ed4956',
    fontWeight: 700,
  },
  inputWrapper: {
    width: '100%',
    padding: 16,
  },
  input: {
    width: '100%',
    height: 48,
    '&:focus': {
      outline: 'none',
    },
    resize: 'none',
    fontFamily: 'Roboto',
    outline: 0,
    border: 'none',
  },
});
export default useStyles;
