import { makeStyles } from '@material-ui/core/styles';
const afterLeft = 18;
const afterWidth = 3;
const afterHeight = 9;
const To = '20px 20px';
const useStyles = makeStyles({
  root: {
    color: '#000000',
    display: 'inline-block',
    position: 'relative',
    width: 40,
    height: 40,
  },
  item1: {
    transformOrigin: To,
    animation: '$spiner 1.2s linear infinite',
    '&:after': {
      content: '""',
      display: 'block',
      position: 'absolute',
      top: 0,
      left: afterLeft,
      width: afterWidth,
      height: afterHeight,
      borderRadius: '20%',
      background: '#000000',
    },
    transform: 'rotate(0deg)',
    animationDelay: '-1.1s',
  },
  item2: {
    transformOrigin: To,
    animation: '$spiner 1.2s linear infinite',
    '&:after': {
      content: '""',
      display: 'block',
      position: 'absolute',
      top: 0,
      left: afterLeft,
      width: afterWidth,
      height: afterHeight,
      borderRadius: '20%',
      background: '#000000',
    },
    transform: 'rotate(30deg)',
    animationDelay: '-1s',
  },
  item3: {
    transformOrigin: To,
    animation: '$spiner 1.2s linear infinite',
    '&:after': {
      content: '""',
      display: 'block',
      position: 'absolute',
      top: 0,
      left: afterLeft,
      width: afterWidth,
      height: afterHeight,
      borderRadius: '20%',
      background: '#000000',
    },
    transform: 'rotate(60deg)',
    animationDelay: '-0.9s',
  },
  item4: {
    transformOrigin: To,
    animation: '$spiner 1.2s linear infinite',
    '&:after': {
      content: '""',
      display: 'block',
      position: 'absolute',
      top: 0,
      left: afterLeft,
      width: afterWidth,
      height: afterHeight,
      borderRadius: '20%',
      background: '#000000',
    },
    transform: 'rotate(90deg)',
    animationDelay: '-0.8s',
  },
  item5: {
    transformOrigin: To,
    animation: '$spiner 1.2s linear infinite',
    '&:after': {
      content: '""',
      display: 'block',
      position: 'absolute',
      top: 0,
      left: afterLeft,
      width: afterWidth,
      height: afterHeight,
      borderRadius: '20%',
      background: '#000000',
    },
    transform: 'rotate(120deg)',
    animationDelay: '-0.7s',
  },
  item6: {
    transformOrigin: To,
    animation: '$spiner 1.2s linear infinite',
    '&:after': {
      content: '""',
      display: 'block',
      position: 'absolute',
      top: 0,
      left: afterLeft,
      width: afterWidth,
      height: afterHeight,
      borderRadius: '20%',
      background: '#000000',
    },
    transform: 'rotate(150deg)',
    animationDelay: '-0.6s',
  },
  item7: {
    transformOrigin: To,
    animation: '$spiner 1.2s linear infinite',
    '&:after': {
      content: '""',
      display: 'block',
      position: 'absolute',
      top: 0,
      left: afterLeft,
      width: afterWidth,
      height: afterHeight,
      borderRadius: '20%',
      background: '#000000',
    },
    transform: 'rotate(180deg)',
    animationDelay: '-0.5s',
  },
  item8: {
    transformOrigin: To,
    animation: '$spiner 1.2s linear infinite',
    '&:after': {
      content: '""',
      display: 'block',
      position: 'absolute',
      top: 0,
      left: afterLeft,
      width: afterWidth,
      height: afterHeight,
      borderRadius: '20%',
      background: '#000000',
    },
    transform: 'rotate(210deg)',
    animationDelay: '-0.4s',
  },
  item9: {
    transformOrigin: To,
    animation: '$spiner 1.2s linear infinite',
    '&:after': {
      content: '""',
      display: 'block',
      position: 'absolute',
      top: 0,
      left: afterLeft,
      width: afterWidth,
      height: afterHeight,
      borderRadius: '20%',
      background: '#000000',
    },
    transform: 'rotate(240deg)',
    animationDelay: '-0.3s',
  },
  item10: {
    transformOrigin: To,
    animation: '$spiner 1.2s linear infinite',
    '&:after': {
      content: '""',
      display: 'block',
      position: 'absolute',
      top: 0,
      left: afterLeft,
      width: afterWidth,
      height: afterHeight,
      borderRadius: '20%',
      background: '#000000',
    },
    transform: 'rotate(270deg)',
    animationDelay: '-0.2s',
  },
  item11: {
    transformOrigin: To,
    animation: '$spiner 1.2s linear infinite',
    '&:after': {
      content: '""',
      display: 'block',
      position: 'absolute',
      top: 0,
      left: afterLeft,
      width: afterWidth,
      height: afterHeight,
      borderRadius: '20%',
      background: '#000000',
    },
    transform: 'rotate(300deg)',
    animationDelay: '-0.1s',
  },
  item12: {
    transformOrigin: To,
    animation: '$spiner 1.2s linear infinite',
    '&:after': {
      content: '""',
      display: 'block',
      position: 'absolute',
      top: 0,
      left: afterLeft,
      width: afterWidth,
      height: afterHeight,
      borderRadius: '20%',
      background: '#000000',
    },
    transform: 'rotate(330deg)',
    animationDelay: '0s',
  },
  '@keyframes spiner': {
    from: { opacity: 1 },
    to: { opacity: 0 },
  },
});
export default useStyles;
