import { makeStyles } from '@material-ui/core/styles';
const useStyles = makeStyles({
  root: {
    height: 55,
    background: '#FFFFFF',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderBottom: '1px solid #dbdbdb',
  },
  logoBox: {
    height: 55,
    width: 360,
    display: 'flex',
    alignItems: 'center',
  },
  logo: {
    color: '#262626',
    margin: 0,
    padding: 0,
    height: 40,
    display: 'block',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textAlign: 'center',
    fontFamily: 'Sofia',
    fontSize: 25,
    fontWeight: 400,
    cursor: 'pointer',
  },
  searchBox: {
    height: 55,
    width: 215,
    display: 'flex',
    alignItems: 'center',
  },
  search: {
    margin: 0,
    padding: 0,
    height: 28,
    width: '100%',
    border: '1px solid #dbdbdb',
    background: '#fafafa',
    textIndent: 10,
  },
  iconBox: {
    height: 55,
    width: 360,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  icon: {
    color: '#262626',
    margin: 0,
    padding: 0,
    height: 40,
    display: 'block',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textAlign: 'center',
    fontFamily: 'Sofia',
    fontSize: 25,
    fontWeight: 400,
  },
  home: {
    width: 22,
    height: 22,
    cursor: 'pointer',
  },
  centerIcon: {
    width: 22,
    height: 22,
    marginLeft: 22,
    cursor: 'pointer',
  },
  avatar: {
    width: 22,
    height: 22,
    borderRadius: '50%',
    marginLeft: 22,
    cursor: 'pointer',
  },
  avatarCircle: {
    width: 30,
    height: 30,
    borderRadius: '50%',
    border: '2px solid #000000',
    position: 'absolute',
    top: -4,
    right: -4,
    cursor: 'pointer',
  },
  dropdownWapper: {
    position: 'relative',
  },
  avatarDropdownBox: {
    width: 230,
    background: '#FFFFFF',
    borderRadius: 6,
    position: 'absolute',
    top: 38,
    right: 0,
    boxShadow: '0 0 5px 1px rgba(0,0,0,.0975)',
  },
  iconDropdown: {
    width: 18,
    height: 18,
    margin: 0,
    padding: 0,
    marginRight: 12,
  },
  profileBox: {
    width: 230,
    height: 37,
    background: '#FFFFFF',
    padding: '8px 16px',
    border: '1px solid #dbdbdb',
    borderBottom: 'none',
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'row',
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: '#FAFAFA',
    },
  },
  settingsBox: {
    width: 230,
    height: 37,
    background: '#FFFFFF',
    padding: '8px 16px',
    borderLeft: '1px solid #dbdbdb',
    borderRight: '1px solid #dbdbdb',
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'row',
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: '#FAFAFA',
    },
  },
  textDropdown: {
    fontSize: 14,
    margin: 0,
    padding: 0,
    width: 170,
  },
  logoutBox: {
    width: 230,
    height: 37,
    background: '#FFFFFF',
    padding: '8px 16px',
    border: '1px solid #dbdbdb',
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'row',
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: '#FAFAFA',
    },
  },
});
export default useStyles;
